M48
; DRILL file {KiCad (6.0.5-0)} date Sunday, October 16, 2022 at 12:17:09 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-10-16T12:17:09-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.372
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.500
%
G90
G05
T1
X-9.525Y3.81
X9.525Y3.81
T2
X-9.525Y9.525
X0.0Y9.525
X9.525Y9.525
T0
M30
